In [1]:
print(12)

12


In [3]:
import torch
print(torch.cuda.is_available())

False


In [7]:
iter(lambda: input('👶: '), '')

In [10]:
lambda: input('👶: ')

<function __main__.<lambda>()>

In [5]:
import torch
a = torch.tensor([[1,2],[2,3]])
b = torch.tensor([[1,0],[0,1]])
print(a*b)

print((a*b).sum()/b.sum())

print(b.sum())

tensor([[1, 0],
        [0, 3]])
tensor(2.)
tensor(2)


In [56]:
import torch
import torch.nn as nn
model = nn.Linear(3,4)
# print(model.state_dict().items())
# print(model.state_dict())
# print(type(model.state_dict()))
# # for k,v in model.state_dict():
# #     print(k,v)
# # dict_k = {"a":1, 'b':"csds"}
# # print(type(dict_k))
# # print(type(dict_k.items()))
# # for step,t in enumerate(dict_k.items()):
# #     print(step,t)

# new_state_dict ={k:v for k,v in model.state_dict().items()} 
# print(new_state_dict)
# print(type(new_state_dict))
# print(new_state_dict['weight'].dtype)

# my_state_dict = {k: v.half() for k,v in model.state_dict().items()}
# print(my_state_dict['weight'].dtype)

# # 保存参数
# ckp = './test/pretrain_test.pth'
# torch.save(model.state_dict(),ckp)

# torch.save(new_state_dict,ckp)

# for k in model.parameters():
#     print(k)

# for s,v in enumerate(model.parameters(),start=10):
#     print(s,v) 


# for n,p in model.named_parameters():
#     print(n,p)


### 加载参数
# print(model.weight)

new_model = nn.Linear(3,4)
ckp = './test/pretrain_test.pth'
state_dict = torch.load(ckp)
print(state_dict)
new_model.load_state_dict(state_dict)

for n,p in new_model.named_parameters():
    print(n,p)





{'weight': tensor([[ 0.1789,  0.5706, -0.3955],
        [ 0.0613, -0.0679,  0.1889],
        [-0.3315, -0.5566,  0.1253],
        [-0.3316, -0.4881, -0.1656]]), 'bias': tensor([-0.4713,  0.3997, -0.5632,  0.1818])}
weight Parameter containing:
tensor([[ 0.1789,  0.5706, -0.3955],
        [ 0.0613, -0.0679,  0.1889],
        [-0.3315, -0.5566,  0.1253],
        [-0.3316, -0.4881, -0.1656]], requires_grad=True)
bias Parameter containing:
tensor([-0.4713,  0.3997, -0.5632,  0.1818], requires_grad=True)


In [ ]:
batch_size = 2
seq_len = 3
vocab_size = 5

logits = torch.randn(batch_size, seq_len, vocab_size)  # 模型输出
labels = torch.tensor([[1, 2, 0], [3, 4, 1]])          # 标签

# 注意要 reshape
loss_fct = nn.CrossEntropyLoss(ignore_index=0, reduction='none')
print(logits.view(-1,vocab_size))
print(labels.view(-1))
#### 交叉熵损失函数是可以把每个序列每一个位置token的损失给计算出来的
loss = loss_fct(logits.view(-1,vocab_size), labels.view(-1)).view(batch_size,seq_len)
# loss = loss.view(batch_size, seq_len)  # 可恢复原来的形状
print(loss)


tensor([[ 0.3459, -2.4720,  0.0103, -0.6584, -1.6558],
        [-0.4128, -0.7754, -1.0513,  0.9078,  0.7612],
        [-0.2757, -0.2913, -0.0886, -0.1356, -0.0994],
        [ 0.1719, -0.4136, -1.0197,  0.2823,  1.9101],
        [-0.6673, -1.6697,  1.1663,  0.4213,  0.3746],
        [-0.8979, -0.6986, -0.9131,  0.4760,  0.7838]])
tensor([1, 2, 0, 3, 4, 1])
tensor([[3.6403, 2.8582, 0.0000],
        [2.0489, 1.5555, 2.3289]])


In [78]:
batch_size = 2
seq_len = 3
vocab_size = 5

logits = torch.randn(batch_size, seq_len, vocab_size)  # 模型输出
labels = torch.tensor([[1, 2, 0], [3, 4, 1]])          # 标签


probs = torch.softmax(logits[:, -1, :], dim=-1)  # 取序列最后一个位置
print(probs)
next_token = torch.argmax(probs, dim=-1).unsqueeze(1)
print(next_token)
next_token = torch.multinomial(probs, num_samples=1)
# print(torch.cat((labels,next_token),-1))
print(next_token)
print(next_token.size())
print(next_token.shape)

tensor([[0.1157, 0.1883, 0.1820, 0.2310, 0.2830],
        [0.0500, 0.0309, 0.6236, 0.2052, 0.0903]])
tensor([[4],
        [2]])
tensor([[2],
        [3]])
torch.Size([2, 1])
torch.Size([2, 1])


In [ ]:
from transformers import AutoTokenizer
messages = [
    {"role": "user", "content": "你好"},
    {"role": "assistant", "content": "你好，有什么我可以帮你的吗？"}
]
tokenizer = AutoTokenizer.from_pretrained('./model')
text = tokenizer.apply_chat_template(messages, tokenize=False)

bos_id = tokenizer('<|im_start|>assistant')
eos_id = tokenizer('<|im_end|>', add_special_tokens=False)
print(f'text = {text}')
print(f'bos_id = {bos_id}')
print(f'eos_id = {eos_id}')
print(tokenizer(text))
print(tokenizer(text)['input_ids'])
tokens = tokenizer("\n")          # 把换行符交给 tokenizer
print("\\n =", tokens)           # 在输出里显示字面量 \n
# 或更可读：
print("tokenizer('\\n') =", tokens)
assistant = tokenizer('assistant')
print(assistant)
user = tokenizer('user')
print(user)
# 将input_ids转回文本
# 对于 transformers 的 fast tokenizer，调用 tokenizer(...) 返回的是一个 BatchEncoding 对象。
# BatchEncoding 既可以像字典一样访问（bos_id['input_ids']），也有属性访问方式（bos_id.input_ids）。
print(tokenizer.decode(bos_id['input_ids'] + [5134, 270, 5183, 5213, 1086, 2155, 2235, 814] + eos_id.input_ids))


text = <|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
你好<|im_end|>
<|im_start|>assistant
你好，有什么我可以帮你的吗？<|im_end|>

bos_id = {'input_ids': [1, 1078, 538, 501], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}
eos_id = {'input_ids': [2], 'token_type_ids': [0], 'attention_mask': [1]}
{'input_ids': [1, 85, 736, 201, 59, 292, 389, 260, 3836, 1861, 501, 2, 201, 1, 320, 275, 201, 5134, 2, 201, 1, 1078, 538, 501, 201, 5134, 270, 5183, 5213, 1086, 2155, 2235, 814, 2, 201], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
[1, 85, 736, 201, 59, 292, 389, 260, 3836, 1861, 501, 2, 201, 1, 320, 275, 201, 5134, 2, 201, 1, 1078, 538, 501, 201, 5134, 270, 5183, 5213, 1086, 2155, 2235, 814, 2, 201]
\n = {'input_ids': [201], 'token_type_ids': [0], 'attention_mask': 

In [9]:
print("A", "B", "C", sep="-", end=" END ")


print("你好", end="")
print("世界")


A-B-C END 你好世界


In [41]:
input_ids = [1,2,3,4]
print(input_ids)
input_ids += [tokenizer.pad_token_id,9] * 5
print(input_ids)

[1, 2, 3, 4]
[1, 2, 3, 4, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9]


In [42]:
samples = []
a = [12,3,3,4]
b = [1,2,3]
# 测试append用法
# samples.append(a)
# print(samples)
# print(samples.append(b))
# print(samples)

# 测试extend用法
samples.extend(a)
print(samples)  
samples.extend(b)
print(samples)
for step, s in enumerate(samples,10):
    print(step,s)

[12, 3, 3, 4]
[12, 3, 3, 4, 1, 2, 3]
10 12
11 3
12 3
13 4
14 1
15 2
16 3


In [75]:
ttt = 10

bos_id = tokenizer('<|im_start|>assistant', return_tensors='pt', max_length=5, padding='max_length', truncation=True)
print(bos_id)
im_start = tokenizer('<|im_start|>', add_special_tokens=True)
print(im_start)
assistant = tokenizer('assistant', add_special_tokens=False)
print(assistant)
eos_id = tokenizer('<|im_end|>', add_special_tokens=False)
print(eos_id)
input_id = tokenizer('你好，中华人民共和国', add_special_tokens=False)
print(input_id)
input_id = tokenizer('你好，中华人民共和国', add_special_tokens=True)
print(input_id)
input_id = tokenizer('<|im_start|>你好，中华人民共和国<|im_end|>\n')
print(input_id)

print(tokenizer.decode([tokenizer.pad_token_id]))




{'input_ids': tensor([[   1, 1078,  538,  501,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 0]])}
{'input_ids': [1], 'token_type_ids': [0], 'attention_mask': [1]}
{'input_ids': [1078, 538, 501], 'token_type_ids': [0, 0, 0], 'attention_mask': [1, 1, 1]}
{'input_ids': [2], 'token_type_ids': [0], 'attention_mask': [1]}
{'input_ids': [5134, 270, 413, 2958, 415, 2666, 1730, 315, 1317], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
{'input_ids': [5134, 270, 413, 2958, 415, 2666, 1730, 315, 1317], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
{'input_ids': [1, 5134, 270, 413, 2958, 415, 2666, 1730, 315, 1317, 2, 201], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
<|endoftext|>


In [47]:
# 测试字典类型的取值方法
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict['a'])
print(my_dict.get('b'))
print(my_dict.get('d', 4))  # 如果key不存在，返回默认值4
# 字典不允许这样取值
# print(my_dict.b)
l = [(k,v) for k,v in my_dict.items() if v>1 ]  # 生成新的元组
print(l)
for k,v in enumerate(l, 11):
    print(k,v)

l_dict = {k:v for k,v in my_dict.items() if v>1}  # 生成新的字典
print(l_dict)

1
2
4
[('b', 2), ('c', 3)]
11 ('b', 2)
12 ('c', 3)
{'b': 2, 'c': 3}


In [59]:
# 使用这段代码查看 jsonl 文件的前 n 行内容

import json
samples = []
# path = './dataset/dpo.jsonl'
path = './dataset/dpo.jsonl'
with open(path, 'r', encoding='utf-8') as f:
    for line_num, line in enumerate(f, 1):
        # print(f'line_num = {line_num}, line = {line}')
        data = json.loads(line.strip())
        # print(f'data = {data}')
        samples.append(data)
        # print(f'samples = {samples}')
        if line_num == 32:
            break
for conv in samples:
    print(conv)
    break
# print(samples)

{'chosen': [{'content': 'How many moles of HBr are required to react with 2 moles of C2H6 to form 2 moles of C2H5Br along with 2 moles of H2?', 'role': 'user'}, {'content': 'To determine the number of moles of HBr required to react with 2 moles of C2H6 (ethane) to form 2 moles of C2H5Br (ethyl bromide) and 2 moles of H2, we need to write the balanced chemical equation for the reaction.\n\nThe reaction is a halogenation reaction, specifically the reaction of ethane with hydrogen bromide (HBr) to form ethyl bromide and hydrogen gas. The balanced chemical equation for this reaction is:\n\n\\[ \\text{C}_2\\text{H}_6 + \\text{HBr} \\rightarrow \\text{C}_2\\text{H}_5\\text{Br} + \\text{H}_2 \\]\n\nHowever, this equation is not balanced as written. To balance it, we need to ensure that the number of atoms of each element on the reactant side is equal to the number of atoms of that element on the product side. The balanced equation is:\n\n\\[ \\text{C}_2\\text{H}_6 + \\text{HBr} \\rightarrow \

In [68]:
print(str([1,2,3]))

[1, 2, 3]


In [76]:
print(1 in [1,2])

True
